### ISSUE TITLE
Meta: GitHub ActionsI fails at the very early stage when invoked from non-maintainer's pull request

### ISSUE THREAD

**Issue by konn** [haskell/haskell-language-server#1155]
After merging 7fa3ff6a64e2ecc19d675a46aff46bffc48c3b1d into my branch konn/expand-splice--lugin, which is a base branch for P.R. #759 , it seems that CIs on GitHub Actions [accidentally stop to work](https://github.com/haskell/haskell-language-server/runs/1641393659?check_suite_focus=true) at the very first stage, with the following error:

```
Run technote-space/auto-cancel-redundant-workflow@1
  with:
3
    GITHUB_TOKEN: ***
4
    EXCLUDE_MERGED: false
5
    MERGE_MESSAGE_PREFIX: Merge pull request
6
    EXCLUDE_TAG_PUSH: true
7

8
==================================================
9
Version:  technote-space/auto-cancel-redundant-workflow@v1.6.6
10
          ebfac7bd22600ff6cdaeb14583443594d6819306
11
Event:    pull_request
12
Action:   synchronize
13
sha:      d6d6ab3aabe96b45397d30838f0896792d9297d9
14
ref:      refs/pull/759/merge
15
Labels:
16
owner:    haskell
17
repo:     haskell-language-server
18

19
Dump context
551
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
552
      at async Promise.all (index 0)
553
      at async Object.execute (/home/runner/work/_actions/technote-space/auto-cancel-redundant-workflow/v1/lib/process.js:35:5)
554
      at async run (/home/runner/work/_actions/technote-space/auto-cancel-redundant-workflow/v1/lib/main.js:13:5) {
555
    name: 'HttpError',
556
    status: 403,
557
    headers: {
558
      'access-control-allow-origin': '*',
559
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
560
      connection: 'close',
561
      'content-encoding': 'gzip',
562
      'content-security-policy': "default-src 'none'",
563
      'content-type': 'application/json; charset=utf-8',
564
      date: 'Mon, 04 Jan 2021 01:39:30 GMT',
565
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
566
      server: 'GitHub.com',
567
      status: '403 Forbidden',
568
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
569
      'transfer-encoding': 'chunked',
570
      vary: 'Accept-Encoding, Accept, X-Requested-With',
571
      'x-content-type-options': 'nosniff',
572
      'x-frame-options': 'deny',
573
      'x-github-media-type': 'github.v3; format=json',
574
      'x-github-request-id': '07C7:7A08:49F22D6:9F15113:5FF271D2',
575
      'x-ratelimit-limit': '1000',
576
      'x-ratelimit-remaining': '927',
577
      'x-ratelimit-reset': '1609727926',
578
      'x-ratelimit-used': '73',
579
      'x-xss-protection': '1; mode=block'
580
    },
581
    request: {
582
      method: 'POST',
583
      url: 'https://api.github.com/repos/haskell/haskell-language-server/actions/runs/460048703/cancel',
584
      headers: {
585
        accept: 'application/vnd.github.v3+json',
586
        'user-agent': 'octokit-core.js/3.2.4 Node.js/12.13.1 (linux; x64)',
587
        authorization: 'token [REDACTED]',
588
        'content-length': 0
589
      },
590
      request: { agent: [Agent], hook: [Function: bound bound register] }
591
    },
592
    documentation_url: 'https://docs.github.com/rest/reference/actions#cancel-a-workflow-run'
593
  }
594
  Error: Resource not accessible by integration
```

Seems like some kind of an access control issue, or perhaps just an upstream glitch.

**Comment by konn** [comment]
Thanks @pepeiborra and @jneira!
