### ISSUE TITLE
*** stack smashing detected ***: terminated

### ISSUE THREAD

**Issue by ilyakooo0** [haskell/haskell-language-server#2633]
### Your environment

Which OS do you use:
- Linux 6273dde0ec9a 5.10.91 NixOS x86_64 GNU/Linux
- VS Code 1.63.2
- Stack

The project has quite a bit of TH: autoexporter and embedding files in binaries.

### Steps to reproduce

I honestly don't know what causes this, but it happens every time I open my private project.

### Expected behaviour

It does not crash

### Actual behaviour

It crashes

### Include debug information

<details>
<summary>
Logs from the VS Code Haskell extension:
</summary>

```
*** stack smashing detected ***: terminated
haskell-language-server-wrapper: callProcess: /home/vscode/.local/bin/haskell-language-server "--lsp" (exit -6): failed
[Error - 8:00:21 AM] Connection to server got closed. Server will not be restarted.
[Error - 8:00:21 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1010893)
	at Object.dispose (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1090976)
	at k.handleConnectionClosed (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1091189)
	at k.handleConnectionClosed (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1151535)
	at t (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1089278)
	at n.invoke (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1012506)
	at a.fire (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1013267)
	at Y (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1000151)
	at n.invoke (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1012506)
	at a.fire (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1013267)
	at g.fireClose (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1024720)
	at Socket.<anonymous> (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1025505)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
[Error - 8:00:21 AM] Request textDocument/codeLens failed.
Error: Connection got disposed.
	at Object.dispose (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1010893)
	at Object.dispose (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1090976)
	at k.handleConnectionClosed (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1091189)
	at k.handleConnectionClosed (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1151535)
	at t (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1089278)
	at n.invoke (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1012506)
	at a.fire (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1013267)
	at Y (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1000151)
	at n.invoke (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1012506)
	at a.fire (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1013267)
	at g.fireClose (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1024720)
	at Socket.<anonymous> (/home/vscode/.vscode-server/extensions/haskell.haskell-1.8.0/dist/extension.js:2:1025505)
	at Socket.emit (events.js:315:20)
	at Pipe.<anonymous> (net.js:673:12)
```

**Comment by jneira** [comment]
I've seen that error before in the cabal issue tracker: https://github.com/haskell/cabal/issues/7456
Does the build succeded out of hls? does the error is throwed if you run `haskell-language-server -d .` in the project root dir (attach logs if it is so, please)?

**Comment by ilyakooo0** [comment]
Yes, the issue is still reproducible when I call `haskell-language-server -d .`.

@jneira I sent you an email with the logs.

**Comment by jneira** [comment]
Thanks, i've took a look and i dont see nothing wrong until the crash. The error is shown just after loading `path/to/Server.hs`.
I guess `haskell-language-server -d path/to/Server.hs` alone will throw it again. If it is so maybe you could indentify some property of that module which might be related with the error

**Comment by pepeiborra** [comment]
Have you tried building an HLS binary from source with `-dynamic`? 

https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#static-binaries

**Comment by bgamari** [comment]
Which GHC version was this observed with?

**Comment by ilyakooo0** [comment]
GHC 8.6.5

**Comment by ilyakooo0** [comment]
I compiled HLS from source with the same version

**Comment by michaelpj** [comment]
Tentatively closing since old and quiet.
